image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: v1.0.0

webhook:
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v1.0.0

certController:
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v1.0.0
